#ifndef ${MYNAME}_H
#define ${MYNAME}_H 0x01000000
/*
 * ${MyName}.${ext}
 * This file was generated by ${generator}
 *   from binary: ${binary-file}
 */

#include <stddef.h>

#ifndef VO_CERTIFICATE_TYPE
#define VO_CERTIFICATE_TYPE

/**
 * Holds a certificate.
 */
typedef struct _voCertificate
{
  /**
   * Pointer to the bytes composing the certificate.
   */
  const char* bytes;

  /**
   * Length of the certificate.
   */
  size_t length;
}
voCertificate;

#endif // end of: #ifndef VO_CERTIFICATE_TYPE

#ifdef __cplusplus
extern "C"
#else
extern
#endif
/**
 * Certificate that grants your application the right to use MyScript.
 * Usage:
 * <pre>
 *   voEngine e = voCreateEngine(VO_MSE_VER, &${myName}, NULL);
 * </pre>
 */
voCertificate ${myName};


#endif // end of: #ifndef ${MYNAME}_H
