/**
 * ${MyName}.${ext}
 * This file was generated by ${generator}
 *   from binary: ${binary-file}
 */

#include <stddef.h>

#ifndef VO_CERTIFICATE_TYPE
#define VO_CERTIFICATE_TYPE

/**
 * Holds a certificate.
 */
typedef struct _voCertificate
{
  /**
   * Pointer to the bytes composing the certificate.
   */
  const char* bytes;

  /**
   * Length of the certificate.
   */
  size_t length;
}
voCertificate;

#endif // end of: #ifndef VO_CERTIFICATE_TYPE

static const char ${myName}_BYTES[] =
{
  ${BYTES}
};

/**
 * Certificate that grants your application the right to use MyScript.
 * Usage:
 * <pre>
 *   voEngine e = voCreateEngine(VO_MSE_VER, &${myName}, NULL);
 * </pre>
 */
voCertificate const ${myName} =
{
  ${myName}_BYTES,
  sizeof(${myName}_BYTES)
};
