/* This file was generated by syncqt. */
#ifndef QT_QTNFC_VERSION_H
#define QT_QTNFC_VERSION_H

#define QTNFC_VERSION_STR "5.7.0"

#define QTNFC_VERSION 0x050700

#endif // QT_QTNFC_VERSION_H
