/* pcl_config.h. Generated by CMake for PCL. */

#define BUILD_RelWithDebInfo
/* PCL version information */
#define PCL_MAJOR_VERSION 1
#define PCL_MINOR_VERSION 6
/* #undef PCL_REVISION_VERSION */
/* #undef PCL_VERSION_PRETTY */
#define PCL_VERSION_CALC(MAJ, MIN, PATCH) (MAJ*100000+MIN*100+PATCH)
#define PCL_VERSION \
    PCL_VERSION_CALC(PCL_MAJOR_VERSION,PCL_MINOR_VERSION,PCL_REVISION_VERSION)
#define PCL_VERSION_COMPARE(OP,MAJ,MIN,PATCH) \
      (PCL_VERSION OP PCL_VERSION_CALC(MAJ,MIN,PATCH))

/* #undef HAVE_TBB */

#define HAVE_OPENNI 1

#define HAVE_QHULL 1

#define HAVE_QHULL_2011 1

/* #undef HAVE_CUDA */

/* #undef USE_ROS */

// SSE macros
/* #undef HAVE_POSIX_MEMALIGN */
/* #undef HAVE_MM_MALLOC */
#define HAVE_SSE4_1_EXTENSIONS
#define HAVE_SSE3_EXTENSIONS
#define HAVE_SSE2_EXTENSIONS
#define HAVE_SSE_EXTENSIONS

#define HAVE_OPENMP

/* Precompile for a minimal set of point types instead of all. */
/* #undef PCL_ONLY_CORE_POINT_TYPES */

#ifdef DISABLE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef DISABLE_QHULL
#undef HAVE_QHULL
#endif

