//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XTResource.rc
//
// This file is a part of the XTREME SHORTCUTBAR MFC class library.
// (c)1998-2012 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_SHORTCUT_RESOURCE_FIRST     9650
#define XTP_SHORTCUT_RESOURCE_LAST      9699


#define XTP_IDB_SHORTCUT_EXPANDBUTTON   9650

#define XTP_ID_SHORTCUT_SHOW_MORE       9651
#define XTP_ID_SHORTCUT_SHOW_FEWER      9652

#define XTP_IDS_SHORTCUT_CONFIGURE      9653

#define XTP_IDS_SHORTCUT_NAVIGATIONPANE  9654
