/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "5.7.0"

#define QT3DCORE_VERSION 0x050700

#endif // QT_QT3DCORE_VERSION_H
