
//{{AFX_CODEJOCK_PRIVATE

#ifndef _XTP_SCHEMA_CURRENT

#define _XTP_SCHEMA_71  (0x1)
#define _XTP_SCHEMA_80  (0x2)
#define _XTP_SCHEMA_85  (0x3)
#define _XTP_SCHEMA_86  (0x4)
#define _XTP_SCHEMA_861 (0x5)
#define _XTP_SCHEMA_87  (0x6)
#define _XTP_SCHEMA_875 (0x7)
#define _XTP_SCHEMA_95  (0x8)
#define _XTP_SCHEMA_97  (0x9)
#define _XTP_SCHEMA_98  (0x10)
#define _XTP_SCHEMA_1000 (0x11)
#define _XTP_SCHEMA_1030 (0x12)
#define _XTP_SCHEMA_1040 (0x14)
#define _XTP_SCHEMA_1041 (0x15)
#define _XTP_SCHEMA_1042 (0x16)
#define _XTP_SCHEMA_1100 (0x17)
#define _XTP_SCHEMA_1120 (0x18)
#define _XTP_SCHEMA_1121 (0x19)
#define _XTP_SCHEMA_1122 (0x20)
#define _XTP_SCHEMA_1200 (0x21)
#define _XTP_SCHEMA_1210 (0x22)
#define _XTP_SCHEMA_1300 (0x23)
#define _XTP_SCHEMA_1310 (0x24)
#define _XTP_SCHEMA_1340 (0x25)
#define _XTP_SCHEMA_1500 (0x26)
#define _XTP_SCHEMA_1510 (0x27)
#define _XTP_SCHEMA_1624 (0x28)
#define _XTP_SCHEMA_1625 (0x29)

#define _XTP_SCHEMA_CURRENT _XTP_SCHEMA_1625

// Old names
#define _XTP_SCHEMA_100 _XTP_SCHEMA_1000
#define _XTP_SCHEMA_103 _XTP_SCHEMA_1030
#define _XTP_SCHEMA_104 _XTP_SCHEMA_1040
#define _XTP_SCHEMA_110 _XTP_SCHEMA_1100
#define _XTP_SCHEMA_112 _XTP_SCHEMA_1120

#endif

//}}AFX_CODEJOCK_PRIVATE
