// Resource.h
//
// This file is a part of the XTREME REPORTCONTROL MFC class library.
// (c)1998-2013 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_REPORT_RESOURCE_FIRST           9550
#define XTP_REPORT_RESOURCE_LAST            9599

#define XTP_IDB_REPORT_GLYPHS               9550
#define XTP_IDB_REPORT_GLYPHS_2013          9551
#define XTP_IDB_REPORT_GLYPHS_VS2012_LIGHT  9552
#define XTP_IDB_REPORT_GLYPHS_VS2012_DARK   9553
#define XTP_IDB_REPORT_GLYPHS_VS2012_BLUE   9554
#define XTP_IDC_REPORT_NODROP               9555
#define XTP_IDS_REPORT_NOGROUPBY            9556
#define XTP_IDS_REPORT_NOITEMS              9557
#define XTP_IDS_REPORT_NOFIELDSAVAILABLE    9558
#define XTP_IDS_REPORT_SORTBY               9559
#define XTP_IDD_REPORT_PRINT_PAGE_SETUP     9560
#define XTP_IDS_REPORT_MARGINS_MM           9561
#define XTP_IDS_REPORT_MARGINS_INCH         9562
#define XTP_IDS_REPORT_FILERT_TEXT_HINT     9563
#define XTP_IDS_REPORT_INCREASING           9564
#define XTP_IDS_REPORT_DECREASING           9565
#define XTP_IDS_REPORT_EXPAND               9566
#define XTP_IDS_REPORT_COLLAPSE             9567

#define XTP_IDC_HEADER_FORMAT               100
#define XTP_IDC_FOOTER_FORMAT               101
#define XTP_IDC_HEADER_FORMAT_BTN           102
#define XTP_IDC_FOOTER_FORMAT_BTN           103
