/*
 * ${MyName}.${ext}
 * This file was generated by ${generator}
 *   from binary: ${binary-file}
 */
package ${package};

/**
 * The <code>${MyName}</code> class provides the bytes of the user
 * certificate used to grant the access to the MyScript technologies.
 */
public final class ${MyName}
{
  /**
   * Returns the bytes of the user certificate.
   *
   * @return The bytes of the user certificate.
   */
  public static final byte[] getBytes()
  {
    return BYTES;
  }

  /**
   * The bytes of the user certificate.
   */
  private static final byte[] BYTES = new byte[]{
    ${BYTES}
  };

} // end of: class ${MyName}
